project_id = "qcm-bancassurance"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
[db]
port = 54322
major_version = 15
[auth]
enabled = true
site_url = "http://localhost:5173"
enable_anonymous_sign_ins = true
[functions.export-csv]
verify_jwt = true
