create view public.questions_public with(security_invoker=on) as select id,section,type,text,options,points from public.questions;
grant select on public.questions_public to anon,authenticated;
create view public.admin_overview with(security_invoker=on) as select count(distinct candidate_id) filter(where status='submitted') candidates,count(*) filter(where status='submitted') completed,count(*) filter(where status='in_progress') in_progress,avg(score) filter(where status='submitted') average_score,percentile_cont(.5) within group(order by score) filter(where status='submitted') median_score,avg((passed::int)*100) filter(where status='submitted') pass_rate,avg(duration_sec) filter(where status='submitted') average_duration_sec from public.attempts where public.is_admin();
create view public.admin_level_distribution with(security_invoker=on) as select level,count(*)::int total from public.attempts where public.is_admin() and status='submitted' group by level;
create view public.admin_question_stats with(security_invoker=on) as select q.id,q.section,q.text,count(a.id) filter(where jsonb_array_length(a.selected)>0)::int responses,avg((a.is_correct::int)*100) success_rate,avg((a.is_partial::int)*100) partial_rate,avg((jsonb_array_length(a.selected)=0)::int*100) unanswered_rate,(select coalesce(jsonb_object_agg(option_id,total),'{}') from(select value#>>'{}' option_id,count(*) total from public.answers aa cross join lateral jsonb_array_elements(aa.selected) where aa.question_id=q.id group by value)s) option_distribution from public.questions q left join public.answers a on a.question_id=q.id and a.is_correct is not null where public.is_admin() group by q.id;
create view public.admin_section_stats with(security_invoker=on) as select q.section,avg(a.points) average_points,avg((a.is_correct::int)*100) success_rate from public.answers a join public.questions q on q.id=a.question_id where public.is_admin() and a.is_correct is not null group by q.section;
create view public.admin_agency_stats with(security_invoker=on) as select c.agency,count(*)::int attempts,avg(a.score) average_score,avg((a.passed::int)*100) pass_rate from public.attempts a join public.candidates c on c.id=a.candidate_id where public.is_admin() and a.status='submitted' group by c.agency;
grant select on public.admin_overview,public.admin_level_distribution,public.admin_question_stats,public.admin_section_stats,public.admin_agency_stats to authenticated;
create or replace function public.admin_timeline(p_days int default 30) returns table(day date,attempts bigint,average_score numeric) language sql stable security invoker set search_path=public as $$select d::date,count(a.id),avg(a.score) from generate_series(current_date-greatest(1,least(p_days,365))+1,current_date,'1 day')d left join attempts a on a.submitted_at>=d and a.submitted_at<d+interval'1 day' and a.status='submitted' where is_admin() group by d order by d$$;grant execute on function public.admin_timeline(int) to authenticated;
